### ISSUE TITLE
Suggestion for esp32 compatibility 

### ISSUE THREAD

**Issue by FHFS** [Azure/azure-iot-arduino-utility#3]
We have been using the Azure-iot-Arduino libraries with the esp32 for a while now. We have found that [socketio_berkley](https://github.com/Azure/azure-c-shared-utility/blob/62223f1e6a661b3afed7af5bc3acc9f5382eb93c/adapters/socketio_berkeley.c) and [tlsio_mbedtls](https://github.com/Azure/azure-c-shared-utility/blob/62223f1e6a661b3afed7af5bc3acc9f5382eb93c/adapters/tlsio_mbedtls.c) work with the esp32 and the lwip/mbedtls libraries from esp-idf.

**Comment by JetstreamRoySprowl** [comment]
Are you able to share or send me the modifications you've made to get this working with ESP32? I'm working with the Azure IoT team on an issue with this combination, and I don't yet have a working build (I'm failing handshake)

**Comment by JetstreamRoySprowl** [comment]
@FHFS - thanks for the tip. Adding this support officially is actually part of a larger pet project of mine (I'm on the Azure IoT team), but it has not floated up much in the priority list yet. Don't know when (or if) I'll get to it, but I would very much like to, and it is on my list!

**Comment by JetstreamRoySprowl** [comment]
It looks like we won't be expanding our Arduino support beyond the Feather M0, Huzzah ESP8266, and Thingdev any time in the near future. Thank you for posting this, though; it will be helpful for other ESP32 users on Arduino.
