### ISSUE TITLE
Error compiling simplesample_http.ino

### ISSUE THREAD

**Issue by msftkevin** [Azure/azure-iot-arduino-utility#8]
I am unable to compile the simplesample_http.ino application provided with the Arduino IDE for the IoTHub as provided by the AzureIoTUtility, AzureIoTProtocol_MQTT, AzureIoTProtocol_HTTP, and AzureIoTHub. 

When attempting to compile, I receive the following error:

In file included from C:\Users\xxxx\Documents\Arduino\libraries\AzureIoTUtility\src/azure_c_shared_utility/lock.h:17:0,

                 from C:\Users\xxxx\Documents\Arduino\libraries\AzureIoTUtility\src/AzureIoTUtility.h:7,

                 from C:\Users\xxxx\Documents\Arduino\libraries\AzureIoTHub\src/AzureIoTHub.h:7,

                 from C:\Users\xxxx\AppData\Local\Temp\arduino_build_830181\sketch\simplesample_http.c:11:

C:\Users\xxxx\Documents\Arduino\libraries\AzureIoTHub\src/sdk/serializer.h:441:79: error: 'REFLECTED_19' undeclared here (not in a function)

     static const REFLECTED_DATA_FROM_DATAPROVIDER ALL_REFLECTED(name) = { &C2(REFLECTED_, C1(DEC(__COUNTER__))) };

                                                                               ^

C:\Users\xxxx\Documents\Arduino\libraries\AzureIoTUtility\src/azure_c_shared_utility/macro_utils.h:4359:18: note: in definition of macro 'C2_'

 #define C2_(x,y) x##y

                  ^

C:\Users\xxxx\Documents\Arduino\libraries\AzureIoTHub\src/sdk/serializer.h:441:76: note: in expansion of macro 'C2'

     static const REFLECTED_DATA_FROM_DATAPROVIDER ALL_REFLECTED(name) = { &C2(REFLECTED_, C1(DEC(__COUNTER__))) };

                                                                            ^

C:\Users\xxxx\Documents\Arduino\libraries\AzureIoTHub\src/sdk/serializer.h:87:5: note: in expansion of macro 'REFLECTED_LIST_HEAD'

     REFLECTED_LIST_HEAD(schemaNamespace)

     ^

C:\Users\xxxx\AppData\Local\Temp\arduino_build_830181\sketch\simplesample_http.c:30:1: note: in expansion of macro 'END_NAMESPACE'

 END_NAMESPACE(WeatherStation);

 ^

**Comment by jbobotek** [comment]
Have you tried this more recently, following these instructions?: https://github.com/Azure/azure-iot-arduino#simple-sample-instructions
